# Creating a feature matrix from a networkx graph

In this notebook we will look at a few ways to quickly create a feature matrix from a networkx graph.

In [1]:
import networkx as nx
import pandas as pd

G = nx.read_gpickle('major_us_cities')

## Node based features

In [2]:
G.nodes(data=True)

[('San Diego, CA', {'location': (-117, 32), 'population': 1355896}),
 ('Las Vegas, NV', {'location': (-115, 36), 'population': 603488}),
 ('Fort Worth, TX', {'location': (-97, 32), 'population': 792727}),
 ('Baltimore, MD', {'location': (-76, 39), 'population': 622104}),
 ('Tucson, AZ', {'location': (-110, 32), 'population': 526116}),
 ('Phoenix, AZ', {'location': (-112, 33), 'population': 1513367}),
 ('New Orleans, LA', {'location': (-90, 29), 'population': 378715}),
 ('Detroit, MI', {'location': (-83, 42), 'population': 688701}),
 ('San Francisco, CA', {'location': (-122, 37), 'population': 837442}),
 ('Cleveland, OH', {'location': (-81, 41), 'population': 390113}),
 ('Mesa, AZ', {'location': (-111, 33), 'population': 457587}),
 ('Long Beach, CA', {'location': (-118, 33), 'population': 469428}),
 ('Albuquerque, NM', {'location': (-106, 35), 'population': 556495}),
 ('Boston, MA', {'location': (-71, 42), 'population': 645966}),
 ('Washington D.C.', {'location': (-77, 38), 'population': 646449}),
 ('Virginia Beach, VA', {'location': (-75, 36), 'population': 448479}),
 ('Wichita, KS', {'location': (-97, 37), 'population': 386552}),
 ('Sacramento, CA', {'location': (-121, 38), 'population': 479686}),
 ('Portland, OR', {'location': (-122, 45), 'population': 609456}),
 ('Omaha, NE', {'location': (-95, 41), 'population': 434353}),
 ('Philadelphia, PA', {'location': (-75, 39), 'population': 1553165}),
 ('Milwaukee, WI', {'location': (-87, 43), 'population': 599164}),
 ('Kansas City, MO', {'location': (-94, 39), 'population': 467007}),
 ('Oklahoma City, OK', {'location': (-97, 35), 'population': 610613}),
 ('Austin, TX', {'location': (-97, 30), 'population': 885400}),
 ('Jacksonville, FL', {'location': (-81, 30), 'population': 842583}),
 ('Minneapolis, MN', {'location': (-93, 44), 'population': 400070}),
 ('Memphis, TN', {'location': (-90, 35), 'population': 653450}),
 ('Los Angeles, CA', {'location': (-118, 34), 'population': 3884307}),
 ('Tulsa, OK', {'location': (-95, 36), 'population': 398121}),
 ('Charlotte, NC', {'location': (-80, 35), 'population': 792862}),
 ('Chicago, IL', {'location': (-87, 41), 'population': 2718782}),
 ('Indianapolis, IN', {'location': (-86, 39), 'population': 843393}),
 ('Arlington, TX', {'location': (-97, 32), 'population': 379577}),
 ('Oakland, CA', {'location': (-122, 37), 'population': 406253}),
 ('Raleigh, NC', {'location': (-78, 35), 'population': 431746}),
 ('Louisville/Jefferson County, KY',
  {'location': (-85, 38), 'population': 609893}),
 ('Seattle, WA', {'location': (-122, 47), 'population': 652405}),
 ('New York, NY', {'location': (-74, 40), 'population': 8405837}),
 ('Colorado Springs, CO', {'location': (-104, 38), 'population': 439886}),
 ('Fresno, CA', {'location': (-119, 36), 'population': 509924}),
 ('Columbus, OH', {'location': (-82, 39), 'population': 822553}),
 ('San Jose, CA', {'location': (-121, 37), 'population': 998537}),
 ('Houston, TX', {'location': (-95, 29), 'population': 2195914}),
 ('Dallas, TX', {'location': (-96, 32), 'population': 1257676}),
 ('San Antonio, TX', {'location': (-98, 29), 'population': 1409019}),
 ('Nashville-Davidson, TN', {'location': (-86, 36), 'population': 634464}),
 ('Miami, FL', {'location': (-80, 25), 'population': 417650}),
 ('Atlanta, GA', {'location': (-84, 33), 'population': 447841}),
 ('Denver, CO', {'location': (-104, 39), 'population': 649495}),
 ('El Paso, TX', {'location': (-106, 31), 'population': 674433})]

In [3]:
# Initialize the dataframe, using the nodes as the index
df = pd.DataFrame(index=G.nodes())

### Extracting attributes

Using `nx.get_node_attributes` it's easy to extract the node attributes in the graph into DataFrame columns.

In [7]:
df['location'] = pd.Series(nx.get_node_attributes(G, 'location'))
df['population'] = pd.Series(nx.get_node_attributes(G, 'population'))

df.head()

                  location  population
San Diego, CA   (-117, 32)     1355896
Las Vegas, NV   (-115, 36)      603488
Fort Worth, TX   (-97, 32)      792727
Baltimore, MD    (-76, 39)      622104
Tucson, AZ      (-110, 32)      526116

### Creating node based features

Most of the networkx functions related to nodes return a dictionary, which can also easily be added to our dataframe.

In [8]:
df['clustering'] = pd.Series(nx.clustering(G))
df['degree'] = pd.Series(G.degree())

df

                                   location  population  clustering  degree
San Diego, CA                    (-117, 32)     1355896    0.745455      11
Las Vegas, NV                    (-115, 36)      603488    0.666667      12
Fort Worth, TX                    (-97, 32)      792727    0.763636      11
Baltimore, MD                     (-76, 39)      622104    0.800000      10
Tucson, AZ                       (-110, 32)      526116    0.750000       8
Phoenix, AZ                      (-112, 33)     1513367    0.694444       9
New Orleans, LA                   (-90, 29)      378715    0.607143       8
Detroit, MI                       (-83, 42)      688701    0.672727      11
San Francisco, CA                (-122, 37)      837442    1.000000       8
Cleveland, OH                     (-81, 41)      390113    0.659341      14
Mesa, AZ                         (-111, 33)      457587    0.750000       8
Long Beach, CA                   (-118, 33)      469428    0.745455      11
Albuquerque, NM                  (-106, 35)      556495    0.523810       7
Boston, MA                        (-71, 42)      645966    1.000000       5
Washington D.C.                   (-77, 38)      646449    0.712121      12
Virginia Beach, VA                (-75, 36)      448479    0.861111       9
Wichita, KS                       (-97, 37)      386552    0.622222      10
Sacramento, CA                   (-121, 38)      479686    0.777778       9
Portland, OR                     (-122, 45)      609456    0.000000       2
Omaha, NE                         (-95, 41)      434353    0.444444       9
Philadelphia, PA                  (-75, 39)     1553165    0.800000      10
Milwaukee, WI                     (-87, 43)      599164    0.666667      10
Kansas City, MO                   (-94, 39)      467007    0.472527      14
Oklahoma City, OK                 (-97, 35)      610613    0.636364      12
Austin, TX                        (-97, 30)      885400    0.892857       8
Jacksonville, FL                  (-81, 30)      842583    0.500000       4
Minneapolis, MN                   (-93, 44)      400070    1.000000       4
Memphis, TN                       (-90, 35)      653450    0.494505      14
Los Angeles, CA                  (-118, 34)     3884307    0.745455      11
Tulsa, OK                         (-95, 36)      398121    0.727273      11
Charlotte, NC                     (-80, 35)      792862    0.636364      12
Chicago, IL                       (-87, 41)     2718782    0.618182      11
Indianapolis, IN                  (-86, 39)      843393    0.641026      13
Arlington, TX                     (-97, 32)      379577    0.763636      11
Oakland, CA                      (-122, 37)      406253    1.000000       8
Raleigh, NC                       (-78, 35)      431746    0.615385      13
Louisville/Jefferson County, KY   (-85, 38)      609893    0.641026      13
Seattle, WA                      (-122, 47)      652405    0.000000       1
New York, NY                      (-74, 40)     8405837    0.833333       9
Colorado Springs, CO             (-104, 38)      439886    0.466667       6
Fresno, CA                       (-119, 36)      509924    0.888889       9
Columbus, OH                      (-82, 39)      822553    0.619048      15
San Jose, CA                     (-121, 37)      998537    1.000000       8
Houston, TX                       (-95, 29)     2195914    0.861111       9
Dallas, TX                        (-96, 32)     1257676    0.763636      11
San Antonio, TX                   (-98, 29)     1409019    1.000000       7
Nashville-Davidson, TN            (-86, 36)      634464    0.589744      13
Miami, FL                         (-80, 25)      417650    0.000000       1
Atlanta, GA                       (-84, 33)      447841    0.611111       9
Denver, CO                       (-104, 39)      649495    0.666667       4
El Paso, TX                      (-106, 31)      674433    0.700000       5

# Edge based features

In [9]:
G.edges(data=True)

[('San Diego, CA', 'Long Beach, CA', {'weight': 151.45008247402757}),
 ('San Diego, CA', 'Tucson, AZ', {'weight': 587.0077247254917}),
 ('San Diego, CA', 'Los Angeles, CA', {'weight': 179.29746717246732}),
 ('San Diego, CA', 'Las Vegas, NV', {'weight': 426.17584242277843}),
 ('San Diego, CA', 'Fresno, CA', {'weight': 507.4313769710358}),
 ('San Diego, CA', 'Phoenix, AZ', {'weight': 480.550984974869}),
 ('San Diego, CA', 'San Jose, CA', {'weight': 669.6772910512424}),
 ('San Diego, CA', 'San Francisco, CA', {'weight': 737.1473892523547}),
 ('San Diego, CA', 'Oakland, CA', {'weight': 730.9953136286227}),
 ('San Diego, CA', 'Mesa, AZ', {'weight': 502.32635614606744}),
 ('San Diego, CA', 'Sacramento, CA', {'weight': 760.0327691692984}),
 ('Las Vegas, NV', 'Long Beach, CA', {'weight': 385.2597725411484}),
 ('Las Vegas, NV', 'Albuquerque, NM', {'weight': 779.953416852203}),
 ('Las Vegas, NV', 'Fresno, CA', {'weight': 418.94992726715964}),
 ('Las Vegas, NV', 'San Jose, CA', {'weight': 614.3930568650861}),
 ('Las Vegas, NV', 'Sacramento, CA', {'weight': 621.6693471839634}),
 ('Las Vegas, NV', 'Tucson, AZ', {'weight': 585.0709975647242}),
 ('Las Vegas, NV', 'Phoenix, AZ', {'weight': 411.9094912462262}),
 ('Las Vegas, NV', 'Los Angeles, CA', {'weight': 367.37280090555305}),
 ('Las Vegas, NV', 'San Francisco, CA', {'weight': 670.2380164875032}),
 ('Las Vegas, NV', 'Oakland, CA', {'weight': 658.3408716278288}),
 ('Las Vegas, NV', 'Mesa, AZ', {'weight': 429.8988310173471}),
 ('Fort Worth, TX', 'San Antonio, TX', {'weight': 386.37486866810514}),
 ('Fort Worth, TX', 'New Orleans, LA', {'weight': 755.8533393744848}),
 ('Fort Worth, TX', 'Tulsa, OK', {'weight': 397.0462555225492}),
 ('Fort Worth, TX', 'Oklahoma City, OK', {'weight': 301.86279118630887}),
 ('Fort Worth, TX', 'Austin, TX', {'weight': 279.2607716124542}),
 ('Fort Worth, TX', 'Wichita, KS', {'weight': 548.2249270170437}),
 ('Fort Worth, TX', 'Kansas City, MO', {'weight': 747.1268740996313}),
 ('Fort Worth, TX', 'Arlington, TX', {'weight': 20.930696675141498}),
 ('Fort Worth, TX', 'Houston, TX', {'weight': 381.3872407940769}),
 ('Fort Worth, TX', 'Dallas, TX', {'weight': 49.93359898977102}),
 ('Fort Worth, TX', 'Memphis, TN', {'weight': 721.7845495553929}),
 ('Baltimore, MD', 'New York, NY', {'weight': 272.38422181145063}),
 ('Baltimore, MD', 'Boston, MA', {'weight': 578.0875135253946}),
 ('Baltimore, MD', 'Washington D.C.', {'weight': 56.16567491112449}),
 ('Baltimore, MD', 'Charlotte, NC', {'weight': 586.2855475627688}),
 ('Baltimore, MD', 'Columbus, OH', {'weight': 551.5744271908803}),
 ('Baltimore, MD', 'Detroit, MI', {'weight': 637.6886783148906}),
 ('Baltimore, MD', 'Virginia Beach, VA', {'weight': 276.4842802839367}),
 ('Baltimore, MD', 'Raleigh, NC', {'weight': 429.0122832219615}),
 ('Baltimore, MD', 'Cleveland, OH', {'weight': 495.1075478023953}),
 ('Baltimore, MD', 'Philadelphia, PA', {'weight': 144.0640481858552}),
 ('Tucson, AZ', 'Long Beach, CA', {'weight': 698.6566667728368}),
 ('Tucson, AZ', 'Albuquerque, NM', {'weight': 510.7965704802782}),
 ('Tucson, AZ', 'Phoenix, AZ', {'weight': 173.37868185485377}),
 ('Tucson, AZ', 'Los Angeles, CA', {'weight': 710.4231699340471}),
 ('Tucson, AZ', 'Mesa, AZ', {'weight': 157.26017307785148}),
 ('Tucson, AZ', 'El Paso, TX', {'weight': 425.41386739988224}),
 ('Phoenix, AZ', 'Long Beach, CA', {'weight': 567.4125390872786}),
 ('Phoenix, AZ', 'Albuquerque, NM', {'weight': 534.0407586326625}),
 ('Phoenix, AZ', 'Fresno, CA', {'weight': 789.7484331199684}),
 ('Phoenix, AZ', 'Los Angeles, CA', {'weight': 573.9011736942347}),
 ('Phoenix, AZ', 'Mesa, AZ', {'weight': 22.79553039579591}),
 ('Phoenix, AZ', 'El Paso, TX', {'weight': 558.7835703774161}),
 ('New Orleans, LA', 'Houston, TX', {'weight': 511.02384244889754}),
 ('New Orleans, LA', 'Nashville-Davidson, TN', {'weight': 755.0752949754904}),
 ('New Orleans, LA', 'Austin, TX', {'weight': 738.1686404349225}),
 ('New Orleans, LA', 'Arlington, TX', {'weight': 735.8026229506348}),
 ('New Orleans, LA', 'Memphis, TN', {'weight': 577.6842584479515}),
 ('New Orleans, LA', 'Dallas, TX', {'weight': 711.0141469371868}),
 ('New Orleans, LA', 'Atlanta, GA', {'weight': 682.384954857707}),
 ('Detroit, MI',
  'Louisville/Jefferson County, KY',
  {'weight': 508.16604231921934}),
 ('Detroit, MI', 'New York, NY', {'weight': 772.9011410671837}),
 ('Detroit, MI', 'Washington D.C.', {'weight': 633.5169854294026}),
 ('Detroit, MI', 'Chicago, IL', {'weight': 381.2299668022458}),
 ('Detroit, MI', 'Philadelphia, PA', {'weight': 710.1462898578072}),
 ('Detroit, MI', 'Columbus, OH', {'weight': 263.423764720247}),
 ('Detroit, MI', 'Nashville-Davidson, TN', {'weight': 756.943864661379}),
 ('Detroit, MI', 'Milwaukee, WI', {'weight': 404.7034896583142}),
 ('Detroit, MI', 'Cleveland, OH', {'weight': 145.0420206213353}),
 ('Detroit, MI', 'Indianapolis, IN', {'weight': 386.1408406535182}),
 ('San Francisco, CA', 'Long Beach, CA', {'weight': 585.6985397766858}),
 ('San Francisco, CA', 'Fresno, CA', {'weight': 260.46960973345125}),
 ('San Francisco, CA', 'Los Angeles, CA', {'weight': 558.7708978607576}),
 ('San Francisco, CA', 'San Jose, CA', {'weight': 67.53245690690382}),
 ('San Francisco, CA', 'Oakland, CA', {'weight': 13.428080525235567}),
 ('San Francisco, CA', 'Sacramento, CA', {'weight': 120.68134676034228}),
 ('Cleveland, OH',
  'Louisville/Jefferson County, KY',
  {'weight': 500.1707647725783}),
 ('Cleveland, OH', 'Chicago, IL', {'weight': 494.246407377749}),
 ('Cleveland, OH', 'Washington D.C.', {'weight': 488.9898877488932}),
 ('Cleveland, OH', 'Columbus, OH', {'weight': 203.17328268011585}),
 ('Cleveland, OH', 'Raleigh, NC', {'weight': 688.6125090133806}),
 ('Cleveland, OH', 'Nashville-Davidson, TN', {'weight': 738.354383567491}),
 ('Cleveland, OH', 'Charlotte, NC', {'weight': 700.9265025725867}),
 ('Cleveland, OH', 'Virginia Beach, VA', {'weight': 713.1719915722457}),
 ('Cleveland, OH', 'Milwaukee, WI', {'weight': 538.5642098043521}),
 ('Cleveland, OH', 'New York, NY', {'weight': 649.4502672715655}),
 ('Cleveland, OH', 'Indianapolis, IN', {'weight': 422.649765785015}),
 ('Cleveland, OH', 'Philadelphia, PA', {'weight': 575.9173040784142}),
 ('Mesa, AZ', 'Long Beach, CA', {'weight': 590.156204210031}),
 ('Mesa, AZ', 'Albuquerque, NM', {'weight': 514.5675468665884}),
 ('Mesa, AZ', 'Los Angeles, CA', {'weight': 596.6944422568216}),
 ('Mesa, AZ', 'El Paso, TX', {'weight': 536.256659972679}),
 ('Long Beach, CA', 'Fresno, CA', {'weight': 360.4704577972272}),
 ('Long Beach, CA', 'Los Angeles, CA', {'weight': 31.69419563651866}),
 ('Long Beach, CA', 'San Jose, CA', {'weight': 518.2330606219175}),
 ('Long Beach, CA', 'Oakland, CA', {'weight': 579.5829987228403}),
 ('Long Beach, CA', 'Sacramento, CA', {'weight': 611.0649790490104}),
 ('Albuquerque, NM', 'Colorado Springs, CO', {'weight': 445.6400042319895}),
 ('Albuquerque, NM', 'Denver, CO', {'weight': 536.4291827646916}),
 ('Albuquerque, NM', 'El Paso, TX', {'weight': 367.88584356108345}),
 ('Boston, MA', 'New York, NY', {'weight': 305.91369197099885}),
 ('Boston, MA', 'Virginia Beach, VA', {'weight': 742.5833491609084}),
 ('Boston, MA', 'Washington D.C.', {'weight': 633.2724255670316}),
 ('Boston, MA', 'Philadelphia, PA', {'weight': 435.35607915456563}),
 ('Washington D.C.',
  'Louisville/Jefferson County, KY',
  {'weight': 760.8391296292245}),
 ('Washington D.C.', 'Philadelphia, PA', {'weight': 198.24371380666594}),
 ('Washington D.C.', 'Columbus, OH', {'weight': 524.8211194461829}),
 ('Washington D.C.', 'Raleigh, NC', {'weight': 375.22530610803875}),
 ('Washington D.C.', 'Indianapolis, IN', {'weight': 789.4034447188161}),
 ('Washington D.C.', 'Virginia Beach, VA', {'weight': 246.445149222362}),
 ('Washington D.C.', 'New York, NY', {'weight': 327.37847523720734}),
 ('Washington D.C.', 'Charlotte, NC', {'weight': 530.1200050223144}),
 ('Virginia Beach, VA', 'New York, NY', {'weight': 461.65690712679395}),
 ('Virginia Beach, VA', 'Philadelphia, PA', {'weight': 351.6415980651635}),
 ('Virginia Beach, VA', 'Columbus, OH', {'weight': 701.8766661783677}),
 ('Virginia Beach, VA', 'Charlotte, NC', {'weight': 472.95036855569816}),
 ('Virginia Beach, VA', 'Raleigh, NC', {'weight': 266.37385856851193}),
 ('Wichita, KS', 'Tulsa, OK', {'weight': 208.1658493855318}),
 ('Wichita, KS', 'Colorado Springs, CO', {'weight': 665.1967107484711}),
 ('Wichita, KS', 'Omaha, NE', {'weight': 412.2771985083082}),
 ('Wichita, KS', 'Oklahoma City, OK', {'weight': 247.36915356065145}),
 ('Wichita, KS', 'Denver, CO', {'weight': 701.4183354835055}),
 ('Wichita, KS', 'Kansas City, MO', {'weight': 286.7887192519942}),
 ('Wichita, KS', 'Arlington, TX', {'weight': 550.8138003458517}),
 ('Wichita, KS', 'Memphis, TN', {'weight': 709.8334440883956}),
 ('Wichita, KS', 'Dallas, TX', {'weight': 548.0572491959326}),
 ('Sacramento, CA', 'Fresno, CA', {'weight': 253.9761318839872}),
 ('Sacramento, CA', 'Los Angeles, CA', {'weight': 581.3180718925387}),
 ('Sacramento, CA', 'San Jose, CA', {'weight': 142.37168354889943}),
 ('Sacramento, CA', 'Oakland, CA', {'weight': 109.82159793013636}),
 ('Sacramento, CA', 'Portland, OR', {'weight': 777.4903265797615}),
 ('Portland, OR', 'Seattle, WA', {'weight': 232.98003496425403}),
 ('Omaha, NE', 'Milwaukee, WI', {'weight': 695.28556620892}),
 ('Omaha, NE', 'Tulsa, OK', {'weight': 566.5584360997123}),
 ('Omaha, NE', 'Chicago, IL', {'weight': 698.9473960021885}),
 ('Omaha, NE', 'Oklahoma City, OK', {'weight': 656.2791186480706}),
 ('Omaha, NE', 'Colorado Springs, CO', {'weight': 796.8394903997096}),
 ('Omaha, NE', 'Kansas City, MO', {'weight': 267.84598679216094}),
 ('Omaha, NE', 'Minneapolis, MN', {'weight': 469.53764600116483}),
 ('Omaha, NE', 'Denver, CO', {'weight': 777.8863249384502}),
 ('Philadelphia, PA', 'New York, NY', {'weight': 129.53654818016477}),
 ('Philadelphia, PA', 'Charlotte, NC', {'weight': 724.7428432701282}),
 ('Philadelphia, PA', 'Columbus, OH', {'weight': 667.0538288622043}),
 ('Philadelphia, PA', 'Raleigh, NC', {'weight': 554.7433742861185}),
 ('Milwaukee, WI',
  'Louisville/Jefferson County, KY',
  {'weight': 561.8059932331587}),
 ('Milwaukee, WI', 'Kansas City, MO', {'weight': 709.5921370123627}),
 ('Milwaukee, WI', 'Chicago, IL', {'weight': 130.97175617954392}),
 ('Milwaukee, WI', 'Columbus, OH', {'weight': 532.5684227398444}),
 ('Milwaukee, WI', 'Nashville-Davidson, TN', {'weight': 770.1467064269982}),
 ('Milwaukee, WI', 'Minneapolis, MN', {'weight': 479.28775968088723}),
 ('Milwaukee, WI', 'Indianapolis, IN', {'weight': 391.5388446310555}),
 ('Kansas City, MO',
  'Louisville/Jefferson County, KY',
  {'weight': 770.6369007007506}),
 ('Kansas City, MO', 'Chicago, IL', {'weight': 663.1871353165795}),
 ('Kansas City, MO', 'Oklahoma City, OK', {'weight': 479.91486422643885}),
 ('Kansas City, MO', 'Minneapolis, MN', {'weight': 662.1046217957743}),
 ('Kansas City, MO', 'Memphis, TN', {'weight': 594.6054291939741}),
 ('Kansas City, MO', 'Dallas, TX', {'weight': 730.377587942699}),
 ('Kansas City, MO', 'Indianapolis, IN', {'weight': 726.2520742478256}),
 ('Kansas City, MO', 'Tulsa, OK', {'weight': 350.19665468058116}),
 ('Kansas City, MO', 'Nashville-Davidson, TN', {'weight': 759.4820459793341}),
 ('Kansas City, MO', 'Arlington, TX', {'weight': 742.8459954761595}),
 ('Oklahoma City, OK', 'Colorado Springs, CO', {'weight': 747.014568661214}),
 ('Oklahoma City, OK', 'Austin, TX', {'weight': 578.2822601911338}),
 ('Oklahoma City, OK', 'San Antonio, TX', {'weight': 677.788567153514}),
 ('Oklahoma City, OK', 'Dallas, TX', {'weight': 306.2597807397289}),
 ('Oklahoma City, OK', 'Memphis, TN', {'weight': 677.9358508494545}),
 ('Oklahoma City, OK', 'Houston, TX', {'weight': 665.217514913665}),
 ('Oklahoma City, OK', 'Tulsa, OK', {'weight': 157.06950410857905}),
 ('Oklahoma City, OK', 'Arlington, TX', {'weight': 305.89535561943643}),
 ('Austin, TX', 'San Antonio, TX', {'weight': 118.36314806535839}),
 ('Austin, TX', 'Tulsa, OK', {'weight': 674.071176589555}),
 ('Austin, TX', 'Arlington, TX', {'weight': 280.8343387749554}),
 ('Austin, TX', 'Houston, TX', {'weight': 235.1985112721572}),
 ('Austin, TX', 'Dallas, TX', {'weight': 292.91146634693376}),
 ('Jacksonville, FL', 'Miami, FL', {'weight': 527.7797119911229}),
 ('Jacksonville, FL', 'Atlanta, GA', {'weight': 458.65574177422604}),
 ('Jacksonville, FL', 'Charlotte, NC', {'weight': 549.2112199489682}),
 ('Jacksonville, FL', 'Raleigh, NC', {'weight': 667.2967757561717}),
 ('Minneapolis, MN', 'Chicago, IL', {'weight': 570.2677332774025}),
 ('Memphis, TN',
  'Louisville/Jefferson County, KY',
  {'weight': 514.7054394176082}),
 ('Memphis, TN', 'Chicago, IL', {'weight': 776.6422940993197}),
 ('Memphis, TN', 'Houston, TX', {'weight': 779.1727315480448}),
 ('Memphis, TN', 'Dallas, TX', {'weight': 675.3316242841653}),
 ('Memphis, TN', 'Indianapolis, IN', {'weight': 617.295220276267}),
 ('Memphis, TN', 'Tulsa, OK', {'weight': 548.09611297848}),
 ('Memphis, TN', 'Nashville-Davidson, TN', {'weight': 315.75011030810685}),
 ('Memphis, TN', 'Arlington, TX', {'weight': 703.6616239985909}),
 ('Memphis, TN', 'Atlanta, GA', {'weight': 541.5047877131989}),
 ('Los Angeles, CA', 'Fresno, CA', {'weight': 329.89973534387246}),
 ('Los Angeles, CA', 'San Jose, CA', {'weight': 491.244577392781}),
 ('Los Angeles, CA', 'Oakland, CA', {'weight': 552.3121684216721}),
 ('Tulsa, OK', 'Houston, TX', {'weight': 712.8495434682451}),
 ('Tulsa, OK', 'Arlington, TX', {'weight': 393.3587398321102}),
 ('Tulsa, OK', 'San Antonio, TX', {'weight': 783.407957742418}),
 ('Tulsa, OK', 'Dallas, TX', {'weight': 382.46410800205336}),
 ('Charlotte, NC',
  'Louisville/Jefferson County, KY',
  {'weight': 551.7938053643243}),
 ('Charlotte, NC', 'Columbus, OH', {'weight': 559.2175271096321}),
 ('Charlotte, NC', 'Raleigh, NC', {'weight': 208.69979892270072}),
 ('Charlotte, NC', 'Indianapolis, IN', {'weight': 688.3846733430148}),
 ('Charlotte, NC', 'Nashville-Davidson, TN', {'weight': 545.8353443886101}),
 ('Charlotte, NC', 'Atlanta, GA', {'weight': 363.83612586974465}),
 ('Chicago, IL',
  'Louisville/Jefferson County, KY',
  {'weight': 433.14201586073085}),
 ('Chicago, IL', 'Columbus, OH', {'weight': 443.294756640302}),
 ('Chicago, IL', 'Nashville-Davidson, TN', {'weight': 639.3273291549567}),
 ('Chicago, IL', 'Indianapolis, IN', {'weight': 265.0916992417503}),
 ('Indianapolis, IN',
  'Louisville/Jefferson County, KY',
  {'weight': 171.93402850524834}),
 ('Indianapolis, IN', 'Columbus, OH', {'weight': 270.3063479826381}),
 ('Indianapolis, IN', 'Raleigh, NC', {'weight': 795.0096232862684}),
 ('Indianapolis, IN', 'Nashville-Davidson, TN', {'weight': 404.3913216129687}),
 ('Indianapolis, IN', 'Atlanta, GA', {'weight': 687.1751452631671}),
 ('Arlington, TX', 'San Antonio, TX', {'weight': 390.8981857027806}),
 ('Arlington, TX', 'Houston, TX', {'weight': 369.5566420759369}),
 ('Arlington, TX', 'Dallas, TX', {'weight': 29.425931317908415}),
 ('Oakland, CA', 'Fresno, CA', {'weight': 250.2309725980516}),
 ('Oakland, CA', 'San Jose, CA', {'weight': 61.90292319070633}),
 ('Raleigh, NC',
  'Louisville/Jefferson County, KY',
  {'weight': 688.7073656910881}),
 ('Raleigh, NC', 'Columbus, OH', {'weight': 601.698772359296}),
 ('Raleigh, NC', 'Nashville-Davidson, TN', {'weight': 733.3988290802547}),
 ('Raleigh, NC', 'New York, NY', {'weight': 680.9077807661519}),
 ('Raleigh, NC', 'Atlanta, GA', {'weight': 571.2185028690484}),
 ('Louisville/Jefferson County, KY',
  'Columbus, OH',
  {'weight': 304.39564005336484}),
 ('Louisville/Jefferson County, KY',
  'Nashville-Davidson, TN',
  {'weight': 249.27549074119767}),
 ('Louisville/Jefferson County, KY',
  'Atlanta, GA',
  {'weight': 515.3935693632964}),
 ('New York, NY', 'Columbus, OH', {'weight': 765.9634514216572}),
 ('Colorado Springs, CO', 'Denver, CO', {'weight': 101.65075926223551}),
 ('Colorado Springs, CO', 'El Paso, TX', {'weight': 797.7517116740046}),
 ('Fresno, CA', 'San Jose, CA', {'weight': 198.66400315450576}),
 ('Columbus, OH', 'Nashville-Davidson, TN', {'weight': 536.2745483969072}),
 ('Columbus, OH', 'Atlanta, GA', {'weight': 701.2644982560505}),
 ('Houston, TX', 'San Antonio, TX', {'weight': 304.1503947555647}),
 ('Houston, TX', 'Dallas, TX', {'weight': 361.54185907832755}),
 ('Dallas, TX', 'San Antonio, TX', {'weight': 406.0065656782324}),
 ('Nashville-Davidson, TN', 'Atlanta, GA', {'weight': 345.6125153590445})]

In [12]:
# Initialize the dataframe, using the edges as the index
df = pd.DataFrame(index=G.edges())

### Extracting attributes

Using `nx.get_edge_attributes`, it's easy to extract the edge attributes in the graph into DataFrame columns.

In [13]:
df['weight'] = pd.Series(nx.get_edge_attributes(G, 'weight'))

df

                                                        weight
(San Diego, CA, Long Beach, CA)                     151.450082
(San Diego, CA, Tucson, AZ)                         587.007725
(San Diego, CA, Los Angeles, CA)                    179.297467
(San Diego, CA, Las Vegas, NV)                      426.175842
(San Diego, CA, Fresno, CA)                         507.431377
(San Diego, CA, Phoenix, AZ)                        480.550985
(San Diego, CA, San Jose, CA)                       669.677291
(San Diego, CA, San Francisco, CA)                  737.147389
(San Diego, CA, Oakland, CA)                        730.995314
(San Diego, CA, Mesa, AZ)                           502.326356
(San Diego, CA, Sacramento, CA)                     760.032769
(Las Vegas, NV, Long Beach, CA)                     385.259773
(Las Vegas, NV, Albuquerque, NM)                    779.953417
(Las Vegas, NV, Fresno, CA)                         418.949927
(Las Vegas, NV, San Jose, CA)                       614.393057
(Las Vegas, NV, Sacramento, CA)                     621.669347
(Las Vegas, NV, Tucson, AZ)                         585.070998
(Las Vegas, NV, Phoenix, AZ)                        411.909491
(Las Vegas, NV, Los Angeles, CA)                    367.372801
(Las Vegas, NV, San Francisco, CA)                  670.238016
(Las Vegas, NV, Oakland, CA)                        658.340872
(Las Vegas, NV, Mesa, AZ)                           429.898831
(Fort Worth, TX, San Antonio, TX)                   386.374869
(Fort Worth, TX, New Orleans, LA)                   755.853339
(Fort Worth, TX, Tulsa, OK)                         397.046256
(Fort Worth, TX, Oklahoma City, OK)                 301.862791
(Fort Worth, TX, Austin, TX)                        279.260772
(Fort Worth, TX, Wichita, KS)                       548.224927
(Fort Worth, TX, Kansas City, MO)                   747.126874
(Fort Worth, TX, Arlington, TX)                      20.930697
...                                                        ...
(Chicago, IL, Nashville-Davidson, TN)               639.327329
(Chicago, IL, Indianapolis, IN)                     265.091699
(Indianapolis, IN, Louisville/Jefferson County,...  171.934029
(Indianapolis, IN, Columbus, OH)                    270.306348
(Indianapolis, IN, Raleigh, NC)                     795.009623
(Indianapolis, IN, Nashville-Davidson, TN)          404.391322
(Indianapolis, IN, Atlanta, GA)                     687.175145
(Arlington, TX, San Antonio, TX)                    390.898186
(Arlington, TX, Houston, TX)                        369.556642
(Arlington, TX, Dallas, TX)                          29.425931
(Oakland, CA, Fresno, CA)                           250.230973
(Oakland, CA, San Jose, CA)                          61.902923
(Raleigh, NC, Louisville/Jefferson County, KY)      688.707366
(Raleigh, NC, Columbus, OH)                         601.698772
(Raleigh, NC, Nashville-Davidson, TN)               733.398829
(Raleigh, NC, New York, NY)                         680.907781
(Raleigh, NC, Atlanta, GA)                          571.218503
(Louisville/Jefferson County, KY, Columbus, OH)     304.395640
(Louisville/Jefferson County, KY, Nashville-Dav...  249.275491
(Louisville/Jefferson County, KY, Atlanta, GA)      515.393569
(New York, NY, Columbus, OH)                        765.963451
(Colorado Springs, CO, Denver, CO)                  101.650759
(Colorado Springs, CO, El Paso, TX)                 797.751712
(Fresno, CA, San Jose, CA)                          198.664003
(Columbus, OH, Nashville-Davidson, TN)              536.274548
(Columbus, OH, Atlanta, GA)                         701.264498
(Houston, TX, San Antonio, TX)                      304.150395
(Houston, TX, Dallas, TX)                           361.541859
(Dallas, TX, San Antonio, TX)                       406.006566
(Nashville-Davidson, TN, Atlanta, GA)               345.612515

[235 rows x 1 columns]

### Creating edge based features

Many of the networkx functions related to edges return a nested data structures. We can extract the relevant data using list comprehension.

In [14]:
df['preferential attachment'] = [i[2] for i in nx.preferential_attachment(G, df.index)]

df

,weight,preferential attachment
"(San Diego, CA, Long Beach, CA)",151.450082,121
"(San Diego, CA, Tucson, AZ)",587.007725,88
"(San Diego, CA, Los Angeles, CA)",179.297467,121
"(San Diego, CA, Las Vegas, NV)",426.175842,132
"(San Diego, CA, Fresno, CA)",507.431377,99
"(San Diego, CA, Phoenix, AZ)",480.550985,99
"(San Diego, CA, San Jose, CA)",669.677291,88
"(San Diego, CA, San Francisco, CA)",737.147389,88
"(San Diego, CA, Oakland, CA)",730.995314,88
"(San Diego, CA, Mesa, AZ)",502.326356,88
"(San Diego, CA, Sacramento, CA)",760.032769,99
"(Las Vegas, NV, Long Beach, CA)",385.259773,132
"(Las Vegas, NV, Albuquerque, NM)",779.953417,84
"(Las Vegas, NV, Fresno, CA)",418.949927,108
"(Las Vegas, NV, San Jose, CA)",614.393057,96
"(Las Vegas, NV, Sacramento, CA)",621.669347,108
"(Las Vegas, NV, Tucson, AZ)",585.070998,96
"(Las Vegas, NV, Phoenix, AZ)",411.909491,108
"(Las Vegas, NV, Los Angeles, CA)",367.372801,132
"(Las Vegas, NV, San Francisco, CA)",670.238016,96
"(Las Vegas, NV, Oakland, CA)",658.340872,96
"(Las Vegas, NV, Mesa, AZ)",429.898831,96
"(Fort Worth, TX, San Antonio, TX)",386.374869,77
"(Fort Worth, TX, New Orleans, LA)",755.853339,88
"(Fort Worth, TX, Tulsa, OK)",397.046256,121
"(Fort Worth, TX, Oklahoma City, OK)",301.862791,132
"(Fort Worth, TX, Austin, TX)",279.260772,88
"(Fort Worth, TX, Wichita, KS)",548.224927,110
"(Fort Worth, TX, Kansas City, MO)",747.126874,154
"(Fort Worth, TX, Arlington, TX)",20.930697,121
...,...,...
"(Chicago, IL, Nashville-Davidson, TN)",639.327329,143
"(Chicago, IL, Indianapolis, IN)",265.091699,143
"(Indianapolis, IN, Louisville/Jefferson County, KY)",171.934029,169
"(Indianapolis, IN, Columbus, OH)",270.306348,195
"(Indianapolis, IN, Raleigh, NC)",795.009623,169
"(Indianapolis, IN, Nashville-Davidson, TN)",404.391322,169
"(Indianapolis, IN, Atlanta, GA)",687.175145,117
"(Arlington, TX, San Antonio, TX)",390.898186,77
"(Arlington, TX, Houston, TX)",369.556642,99
"(Arlington, TX, Dallas, TX)",29.425931,121
"(Oakland, CA, Fresno, CA)",250.230973,72
"(Oakland, CA, San Jose, CA)",61.902923,64
"(Raleigh, NC, Louisville/Jefferson County, KY)",688.707366,169
"(Raleigh, NC, Columbus, OH)",601.698772,195
"(Raleigh, NC, Nashville-Davidson, TN)",733.398829,169
"(Raleigh, NC, New York, NY)",680.907781,117
"(Raleigh, NC, Atlanta, GA)",571.218503,117
"(Louisville/Jefferson County, KY, Columbus, OH)",304.395640,195
"(Louisville/Jefferson County, KY, Nashville-Davidson, TN)",249.275491,169
"(Louisville/Jefferson County, KY, Atlanta, GA)",515.393569,117
"(New York, NY, Columbus, OH)",765.963451,135
"(Colorado Springs, CO, Denver, CO)",101.650759,24
"(Colorado Springs, CO, El Paso, TX)",797.751712,30
"(Fresno, CA, San Jose, CA)",198.664003,72
"(Columbus, OH, Nashville-Davidson, TN)",536.274548,195
"(Columbus, OH, Atlanta, GA)",701.264498,135
"(Houston, TX, San Antonio, TX)",304.150395,63
"(Houston, TX, Dallas, TX)",361.541859,99
"(Dallas, TX, San Antonio, TX)",406.006566,77
"(Nashville-Davidson, TN, Atlanta, GA)",345.612515,117

In the case where the function expects two nodes to be passed in, we can map the index to a lamda function.

In [15]:
df['Common Neighbors'] = df.index.map(lambda city: len(list(nx.common_neighbors(G, city[0], city[1]))))

df

,weight,preferential attachment,Common Neighbors
"(San Diego, CA, Long Beach, CA)",151.450082,121,10
"(San Diego, CA, Tucson, AZ)",587.007725,88,5
"(San Diego, CA, Los Angeles, CA)",179.297467,121,10
"(San Diego, CA, Las Vegas, NV)",426.175842,132,10
"(San Diego, CA, Fresno, CA)",507.431377,99,8
"(San Diego, CA, Phoenix, AZ)",480.550985,99,6
"(San Diego, CA, San Jose, CA)",669.677291,88,7
"(San Diego, CA, San Francisco, CA)",737.147389,88,7
"(San Diego, CA, Oakland, CA)",730.995314,88,7
"(San Diego, CA, Mesa, AZ)",502.326356,88,5
"(San Diego, CA, Sacramento, CA)",760.032769,99,7
"(Las Vegas, NV, Long Beach, CA)",385.259773,132,10
"(Las Vegas, NV, Albuquerque, NM)",779.953417,84,3
"(Las Vegas, NV, Fresno, CA)",418.949927,108,8
"(Las Vegas, NV, San Jose, CA)",614.393057,96,7
"(Las Vegas, NV, Sacramento, CA)",621.669347,108,7
"(Las Vegas, NV, Tucson, AZ)",585.070998,96,6
"(Las Vegas, NV, Phoenix, AZ)",411.909491,108,7
"(Las Vegas, NV, Los Angeles, CA)",367.372801,132,10
"(Las Vegas, NV, San Francisco, CA)",670.238016,96,7
"(Las Vegas, NV, Oakland, CA)",658.340872,96,7
"(Las Vegas, NV, Mesa, AZ)",429.898831,96,6
"(Fort Worth, TX, San Antonio, TX)",386.374869,77,6
"(Fort Worth, TX, New Orleans, LA)",755.853339,88,5
"(Fort Worth, TX, Tulsa, OK)",397.046256,121,9
"(Fort Worth, TX, Oklahoma City, OK)",301.862791,132,9
"(Fort Worth, TX, Austin, TX)",279.260772,88,7
"(Fort Worth, TX, Wichita, KS)",548.224927,110,6
"(Fort Worth, TX, Kansas City, MO)",747.126874,154,6
"(Fort Worth, TX, Arlington, TX)",20.930697,121,10
...,...,...,...
"(Chicago, IL, Nashville-Davidson, TN)",639.327329,143,8
"(Chicago, IL, Indianapolis, IN)",265.091699,143,8
"(Indianapolis, IN, Louisville/Jefferson County, KY)",171.934029,169,12
"(Indianapolis, IN, Columbus, OH)",270.306348,195,10
"(Indianapolis, IN, Raleigh, NC)",795.009623,169,7
"(Indianapolis, IN, Nashville-Davidson, TN)",404.391322,169,11
"(Indianapolis, IN, Atlanta, GA)",687.175145,117,6
"(Arlington, TX, San Antonio, TX)",390.898186,77,6
"(Arlington, TX, Houston, TX)",369.556642,99,8
"(Arlington, TX, Dallas, TX)",29.425931,121,10
"(Oakland, CA, Fresno, CA)",250.230973,72,7
"(Oakland, CA, San Jose, CA)",61.902923,64,7
"(Raleigh, NC, Louisville/Jefferson County, KY)",688.707366,169,7
"(Raleigh, NC, Columbus, OH)",601.698772,195,11
"(Raleigh, NC, Nashville-Davidson, TN)",733.398829,169,6
"(Raleigh, NC, New York, NY)",680.907781,117,6
"(Raleigh, NC, Atlanta, GA)",571.218503,117,6
"(Louisville/Jefferson County, KY, Columbus, OH)",304.395640,195,10
"(Louisville/Jefferson County, KY, Nashville-Davidson, TN)",249.275491,169,11
"(Louisville/Jefferson County, KY, Atlanta, GA)",515.393569,117,6
"(New York, NY, Columbus, OH)",765.963451,135,7
"(Colorado Springs, CO, Denver, CO)",101.650759,24,3
"(Colorado Springs, CO, El Paso, TX)",797.751712,30,1
"(Fresno, CA, San Jose, CA)",198.664003,72,7
"(Columbus, OH, Nashville-Davidson, TN)",536.274548,195,9
"(Columbus, OH, Atlanta, GA)",701.264498,135,5
"(Houston, TX, San Antonio, TX)",304.150395,63,6
"(Houston, TX, Dallas, TX)",361.541859,99,8
"(Dallas, TX, San Antonio, TX)",406.006566,77,6
"(Nashville-Davidson, TN, Atlanta, GA)",345.612515,117,7